@baseUrl = http://localhost:3000/
@accessToken = {{authLogin.response.body.token}}

### APPController teste
# @name AppControllerGetHello
GET {{baseUrl}}teste
Authorization: Bearer {{accessToken}}

### AppControllerConceitoTeste
# @name AppControllerConceitoTeste
GET {{baseUrl}}conceitos/teste

### Buscar todos recados
# @name AppControllerRecados
GET {{baseUrl}}recados
?limit=1
&page=3
Authorization: Bearer {{accessToken}}

### Buscar todos recados com status code modificado
GET {{baseUrl}}recados/todos
?limit=1
&page=1

### Buscar recado por id
GET {{baseUrl}}recados/3
#teste: 12345
Authorization: Bearer {{accessToken}}

### Criar um recado
POST {{baseUrl}}recados
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "texto": "Recado especial de natal.",
    "para":[{"id":1}, {"id":2}]
}


### Atualizar um recado
PATCH {{baseUrl}}recados/6
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
   "texto": "Mensagem atualizada 2",
   "para": [{"id":3}],
   "lido": true
}


### Remover recado
DELETE {{baseUrl}}recados/5
Authorization: Bearer {{accessToken}}




// API ROLES

### Buscar todos roles
GET {{baseUrl}}roles
Authorization: Bearer {{accessToken}}

### Criar uma role
POST {{baseUrl}}roles
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
    "nome": "maintainer",
    "descricao": "Role de administradores do sistema"
}


// API PESSOAS

### Buscar todas pessoas
GET {{baseUrl}}pessoas
Authorization: Bearer {{accessToken}}

### Buscar pessoa por id
GET {{baseUrl}}pessoas/3

### Criar uma pessoa
POST {{baseUrl}}pessoas
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "email": "novoUsuario@app.com",
    "password": "12345678",
    "nome":"Novo usuario teste",
    "roles":[{"id": 3}]
}

### Remover Pessoa
DELETE {{baseUrl}}pessoas/3
Authorization: Bearer {{accessToken}}


### Atualizar uma pessoa
PATCH {{baseUrl}}pessoas/16
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "password": "12345678"
}

#{
#    "nome":"nova pessoa",
#    "email": "sofia@app.com",
#    "password":
#    "roles":[{"id": 1}, {"id": 2}, {"id": 3}]
#}


//API AUTH

### Login Auth
# @name authLogin
POST {{baseUrl}}auth/login
Content-Type: application/json

{
    "email": "joao@app.com",
    "password": "12345678"
}


### Refresh token
POST {{baseUrl}}auth/renovar
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6ImpvYW9AYXBwLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTczNjA5MTAxOCwiZXhwIjoxNzM2MDk0NjE4LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.IECkLkJSzdKtGkDknLIMMuWZ9JO1xPe_xoNWg0Rus9Y"
}


### Upload - foto usuario no Banco de dados
POST {{baseUrl}}pessoas/upload-foto-banco
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----DelimitadorHttp

------DelimitadorHttp
Content-Disposition: form-data; name="foto"; filename="arquivo.png"
Content-Type: image/png

< ./dev/images/arquivo.png
------DelimitadorHttp--


### Upload - foto usuario no file system
POST {{baseUrl}}pessoas/upload-foto-file-system
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----DelimitadorHttp

------DelimitadorHttp
Content-Disposition: form-data; name="foto"; filename="arquivo.png"
Content-Type: image/png

< ./dev/images/arquivo.png
------DelimitadorHttp--


### Get Fotos
GET {{baseUrl}}pictures/16.png
