@baseUrl = http://localhost:3000/

### APPController teste
# @name AppControllerGetHello
GET {{baseUrl}}teste
Authorization: Bearer 1234567

### AppControllerConceitoTeste
# @name AppControllerConceitoTeste
GET {{baseUrl}}conceitos/teste

### Buscar todos recados
# @name AppControllerRecados
GET {{baseUrl}}recados
?limit=0
&page=0
Authorization: Bearer 1234567

### Buscar todos recados com status code modificado
GET {{baseUrl}}recados/todos
?limit=1
&page=1

### Buscar recado por id
GET {{baseUrl}}recados/3
#teste: 12345
Authorization: Bearer 1234567

### Criar um recado
POST {{baseUrl}}recados
Content-Type: application/json
Authorization: Bearer 1234567

{
    "texto": "Novo recado XPTO ",
    "de":{"id": 2},
    "para":[{"id":1}]
}


### Atualizar um recado
PATCH {{baseUrl}}recados/4
Content-Type: application/json

{
   "texto": "Mensagem atualizada 4",
   "de":{"id": 14},
   "para": [{"id":3}],
   "lido": true
}


### Remover recado
DELETE {{baseUrl}}recados/2




// API ROLES

### Buscar todos roles
GET {{baseUrl}}roles
Authorization: Bearer 1234567

### Criar uma role
POST {{baseUrl}}roles
Content-Type: application/json
Authorization: Bearer 1234567


{
    "nome": "maintainer",
    "descricao": "Role de administradores do sistema"
}


// API PESSOAS

### Buscar todas pessoas
GET {{baseUrl}}pessoas
Authorization: Bearer 1234567

### Buscar pessoa por id
GET {{baseUrl}}pessoas/3

### Criar uma pessoa
POST {{baseUrl}}pessoas
Content-Type: application/json
Authorization: Bearer 1234567

{
    "email": "outro_novo_dennys@app.com",
    "password": "12345678910",
    "nome":"Dennys Arantes Novo Outro",
    "roles":[{"id": 1},{"id": 2}, {"id":3} ]
}

### Remover Pessoa
DELETE {{baseUrl}}pessoas/15


### Atualizar uma pessoa
PATCH {{baseUrl}}pessoas/4
Content-Type: application/json
Authorization: Bearer 1234567

{
    "password": "12345678"
}

#{
#    "nome":"nova pessoa",
#    "email": "sofia@app.com",
#    "password":
#    "roles":[{"id": 1}, {"id": 2}, {"id": 3}]
#}


//API AUTH

### Autenticar Auth
POST {{baseUrl}}auth/autenticar
Content-Type: application/json

{
    "email": "dennys@app.com",
    "password": "12345678"
}
